/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// cats-dogs
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78002/CNN --prefix cats-dogs --checkpoint-file trained/ai85-catsdogs-qat8-q.pth.tar --config-file networks/cats-dogs-hwc-no-fifo.yaml --softmax --device MAX78002 --timer 0 --display-checkpoint --verbose

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

// Other includes
#include "mxc_device.h"
#include "mxc_sys.h"
#include "fcr_regs.h"
#include "icc.h"
#include "led.h"
#include "tmr.h"
#include "dma.h"
#include "pb.h"
#include "weights.h"
#include "sampledata.h"
#include "mxc_delay.h"
#include "camera.h"

// define for image, camera, and ascii art
#define ASCII_ART
#define IMAGE_SIZE_X (64 * 2)
#define IMAGE_SIZE_Y (64 * 2)
#define CAMERA_FREQ (5 * 1000 * 1000)

// RGB565 buffer for TFT
uint8_t data565[IMAGE_SIZE_X * 2];

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

volatile uint32_t cnn_time; // Stopwatch

// Get data
#ifdef USE_SAMPLEDATA
// Data input: HWC 3x128x128 (49152 bytes total/ 16384 bytes per channel):
static const uint32_t input_0[] = SAMPLE_INPUT_0;
#else
static uint32_t input_0[IMAGE_SIZE_X * IMAGE_SIZE_Y]; // buffer for camera image
#endif

/*************************************************************/
#ifdef ASCII_ART
//char * brightness = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. "; // standard
char *brightness = "@%#*+=-:."; // simple
#define RATIO 2 // ratio of scaling down the image to display in ascii

void asciiart(uint8_t *img) {
  int skip_x, skip_y;
  uint8_t r, g, b, Y;
  uint8_t *srcPtr = img;
  int l = strlen(brightness) - 1;

  skip_x = RATIO;
  skip_y = RATIO;
  for (int i = 0; i < IMAGE_SIZE_Y; i++) {
    for (int j = 0; j < IMAGE_SIZE_X; j++) {
      //0x00bbggrr, convert to [0,255] range
      r = *srcPtr++ ^ 0x80;
      g = *(srcPtr++) ^ 0x80;
      b = *(srcPtr++) ^ 0x80;

      srcPtr++; //skip msb=0x00

      // Y = 0.2126 * r + 0.7152 * g + 0.0722 * b ;
      Y = (3 * r + b + 4 * g) >> 3; // simple luminance conversion
      if ((skip_x == RATIO) && (skip_y == RATIO))
        printf("%c", brightness[l - (Y * l / 255)]);

      skip_x++;
      if (skip_x > RATIO)
        skip_x = 1;
    }
    skip_y++;
    if (skip_y > RATIO) {
      printf("\n");
      skip_y = 1;
    }
  }
}
#endif

/*************************************************************/

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// Data input: HWC 3x128x128 (49152 bytes total / 16384 bytes per channel):
void load_input(void)
{
    // This function loads the sample data input -- replace with actual data

    int i;
    const uint32_t *in0 = input_0;

    for (i = 0; i < 16384; i++) {
        // Remove the following line if there is no risk that the source would overrun the FIFO:
        while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
        *((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
    }
}


/***************************************************************************/
void capture_process_camera(void)
{
    uint8_t *raw;
    uint32_t imgLen;
    uint32_t w, h;

    int cnt = 0;

    uint8_t r, g, b;
    uint16_t rgb;
    int j = 0;

    uint8_t *data = NULL;
    stream_stat_t *stat;

    camera_start_capture_image();

    // Get the details of the image from the camera driver.
    camera_get_image(&raw, &imgLen, &w, &h);
    printf("W:%d H:%d L:%d \n", w, h, imgLen);

    // Get image line by line
    for (int row = 0; row < h; row++) {
        // Wait until camera streaming buffer is full
        while ((data = get_camera_stream_buffer()) == NULL) {
            if (camera_is_image_rcv()) {
                break;
            }
        }

        //LED_Toggle(LED2);
        j = 0;

        for (int k = 0; k < 4 * w; k += 4) {
            // data format: 0x00bbggrr
            r = data[k];
            g = data[k + 1];
            b = data[k + 2];
            //skip k+3

            // change the range from [0,255] to [-128,127] and store in buffer for CNN
            input_0[cnt++] = ((b << 16) | (g << 8) | r) ^ 0x00808080;

            // convert to RGB656 for display
            rgb = ((r & 0b11111000) << 8) | ((g & 0b11111100) << 3) | (b >> 3);
            data565[j] = (rgb >> 8) & 0xFF;
            data565[j + 1] = rgb & 0xFF;
            j += 2;
        }

        //LED_Toggle(LED2);
        // Release stream buffer
        release_camera_stream_buffer();
    }

    //camera_sleep(1);
    stat = get_camera_stream_statistic();

    if (stat->overflow_count > 0) {
        printf("OVERFLOW DISP = %d\n", stat->overflow_count);
        LED_On(LED2); // Turn on red LED if overflow detected
        while (1) {}
    }
}

/***************************************************************************/

void softmax_layer(void)
{
    cnn_unload((uint32_t *) ml_data);
    softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;
  int ret = 0;
  int result[CNN_NUM_OUTPUTS]; // = {0};
  int dma_channel;

  // Classes
  //const char classes[CNN_NUM_OUTPUTS][20] = { "Cheesecake", "Chocolate Cake", "Pie", "Red Velvet Cake"
  //    };
  const char classes[CNN_NUM_OUTPUTS][20] = { "Cat", "Dog" };

  #if defined(BOARD_FTHR_REVA)
      // Wait for PMIC 1.8V to become available, about 180ms after power up.
      MXC_Delay(200000);
      /* Enable camera power */
      Camera_Power(POWER_ON);
      //MXC_Delay(300000);
      printf("\n\nCats-vs-Dogs Feather Demo\n");
  #endif

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test cats-dogs_gen ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  //cnn_start(); // Start CNN processing
  //load_input(); // Load data input via FIFO

/***************************************************************************/
  // For Camera Initialization
  // Initialize DMA for camera interface
  MXC_DMA_Init();
  dma_channel = MXC_DMA_AcquireChannel();

  // Initialize camera.
  printf("Init Camera.\n");
  camera_init(CAMERA_FREQ);

  ret = camera_setup(IMAGE_SIZE_X, IMAGE_SIZE_Y, PIXFORMAT_RGB888, FIFO_THREE_BYTE, STREAMING_DMA,
                     dma_channel);
  if (ret != STATUS_OK) {
      printf("Error returned from setting up camera. Error %d\n", ret);
      return -1;
  }

  camera_write_reg(0x11, 0x0); // set camera clock prescaller to prevent streaming overflow
/***************************************************************************/
  printf("********** Press PB1(SW1) to capture an image **********\r\n");
  while (!PB_Get(0)) {}

  // Enable CNN clock
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN);

  while (1) {
      LED_Off(LED1);
      LED_Off(LED2);
/***************************************************************************/
      capture_process_camera(); //capture camera
      cnn_start(); // Start CNN processing
      load_input(); // Load data input via FIFO

      // while (cnn_time == 0)
      // MXC_LP_EnterSleepMode(); // Wait for CNN

      SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk; // SLEEPDEEP=0
      while (cnn_time == 0) {
            __WFI(); // Wait for CNN interrupt
        }

        // if (check_output() != CNN_OK) fail();
        softmax_layer();

        printf("\n*** PASS ***\n\n");

    #ifdef CNN_INFERENCE_TIMER
        printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
    #endif

        //cnn_disable(); // Shut down CNN clock, disable peripheral

        printf("Classification results:\n");
        for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
            digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
            tens = digs % 10;
            digs = digs / 10;
            result[i] = digs;
            printf("[%7d] -> %20s: %d.%d%%\r\n", ml_data[i], classes[i], result[i],
                   tens);
        }

        printf("\n");

    #ifdef ASCII_ART
        asciiart((uint8_t *)input_0);
        printf("********** Press PB1(SW1) to capture an image **********\r\n");
    #endif
        while (!PB_Get(0)) {}
    }//while end
    return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 51,368,960 ops (50,432,000 macc; 936,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 7,340,032 ops (7,077,888 macc; 262,144 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 19,267,584 ops (18,874,368 macc; 393,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 19,070,976 ops (18,874,368 macc; 196,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 4,792,320 ops (4,718,592 macc; 73,728 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 600,064 ops (589,824 macc; 10,240 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 295,936 ops (294,912 macc; 1,024 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 2,048 ops (2,048 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 57,776 bytes out of 2,396,160 bytes total (2.4%)
  Bias memory:   2 bytes out of 8,192 bytes total (0.0%)
*/

